name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgmp-dev libssl-dev
        wget https://crypto.stanford.edu/pbc/files/pbc-0.5.14.tar.gz
        tar -xzf pbc-0.5.14.tar.gz
        cd pbc-0.5.14
        ./configure
        make
        sudo make install

    - name: Build Charm
      run: |
        ./configure.sh
        make

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pyparsing==2.1.5 hypothesis

    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        pytest
